apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}:{{ .Values.image.pullPolicy }}
        name: techtrends
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        resources:
          requests: {{ .Values.resources.requests.cpu }}:{{ .Values.resources.requests.memory }}
        livenessProbe:
          httpGet: {{ .Values.livenessProbe.httpGet.path }}:{{ .Values.ports.containerPort }}

        readinessProbe:
          httpGet: {{ .Values.readinessProbe.httpGet.path }}:{{ .Values.ports.containerPort }}